### PR TITLE
Some minor fixes.

### PR DESCRIPTION
**Pull request by joshelser**

### CODE REVIEW

**Comment by joshelser** [comment]
Hmm. Not sure why travis failed, though. I dont' recognize the file it's complaining about. Happy to fix if it's something I did.

**Comment by mjwall** [comment]
Oh, travis is not working.  Can be ignored for now

**Comment by joshelser** [comment]
Whew, glad it wasn't me :). Thanks for the merge. I'll try to run through it again tonight on a clean pull to make sure I didn't botch anything else!

**Comment by joshelser** [comment]
Reran with 200775f5 this morning and it all started up correctly. :+1:

**Comment by mjwall** [comment]
Great, thanks Josh

**Pull request merged**
